logging:
  level:
    im:
      zhaojun:
        common: debug
  path: ${user.home}/.zfile/logs

server:
  port: 8080
  servlet:
    context-path: ''


spring:
  cache:
    type: caffeine
#    type: redis
  datasource:
    # 初始化数据导入
    data: classpath*:db/data.sql
    initialization-mode: always
    continue-on-error: true

    # h2 内存数据库 配置
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.zfile/db/zfile-demo
    username: zfile-demo
    password: 123456

    # MySQL 配置
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/zfile-demo?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  resources:
    chain:
      gzipped: true
zfile:
  cache:
    timeout: 300
  constant:
    header: header.md
    footer: footer.md
    password: password.txt

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      defaultExpireInMillis: 6000000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      defaultExpireInMillis: 3600000
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
      password: 12345